### ISSUE TITLE
More user-friendly error messages when trying to do things like login --non-interactive

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#202]
Can we avoid printing the go stacktrace on errors like this?

```
$ bosh2 login -n -e mybosh
[CLI] 2017/04/20 13:45:53 ERROR - Panic: Cannot ask for input in non-interactive UI
********************
goroutine 1 [running]:
runtime/debug.Stack(0xb303a0, 0xc42035e060, 0xc420262680)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
main.handlePanic()
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:110 +0x2e1
panic(0xa6d880, 0xc420262680)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cloudfoundry/bosh-cli/cmd.Cmd.Execute.func1(0xc420154548)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/cmd.go:44 +0xe7
panic(0xa6d880, 0xc420262680)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cloudfoundry/bosh-cli/ui.(*nonInteractiveUI).AskForText(0xc4201f5840, 0xb79883, 0x8, 0x0, 0x0, 0x0, 0xee7d20)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/ui/non_interactive.go:44 +0x6d
github.com/cloudfoundry/bosh-cli/ui.(*ConfUI).AskForText(0xc420131140, 0xb79883, 0x8, 0xc4201472f0, 0x4b88a1, 0xc42021b500, 0xc420201740)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/ui/conf_ui.go:75 +0x47
github.com/cloudfoundry/bosh-cli/cmd.BasicLoginStrategy.askForCreds(0xc4202260e0, 0xee7d20, 0xc42024e300, 0xee8720, 0xc420131140, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/basic_login_strategy.go:87 +0x15c
github.com/cloudfoundry/bosh-cli/cmd.BasicLoginStrategy.tryOnce(0xc4202260e0, 0xee7d20, 0xc42024e300, 0xee8720, 0xc420131140, 0xc420201740, 0x16, 0x0, 0x0, 0x0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/basic_login_strategy.go:51 +0x80
github.com/cloudfoundry/bosh-cli/cmd.BasicLoginStrategy.Try(0xc4202260e0, 0xee7d20, 0xc42024e300, 0xee8720, 0xc420131140, 0xc4202625b0, 0x9)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/basic_login_strategy.go:35 +0x118
github.com/cloudfoundry/bosh-cli/cmd.(*BasicLoginStrategy).Try(0xc42021ecc0, 0x5, 0xb77eda)
	<autogenerated>:19 +0x6e
github.com/cloudfoundry/bosh-cli/cmd.LogInCmd.Run(0xede7e0, 0xc42021ecc0, 0xede8a0, 0xc42022e310, 0xeeb3a0, 0xc42022c240, 0x0, 0x0)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/log_in.go:43 +0x1be
github.com/cloudfoundry/bosh-cli/cmd.Cmd.Execute(0xbf73e0, 0xabe80f, 0xe, 0x7ffdd7fe11a9, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/cmd.go:104 +0x4ad5
main.main()
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:35 +0x75d

********************
Exit code 1
```

**Comment by dpb587-pivotal** [comment]
Agreed - unfriendly UX. Relevant code [here](https://github.com/cloudfoundry/bosh-cli/blob/47ea06453290186de2610150498d3901d16c4131/ui/non_interactive.go#L44-L52) - seems like we could return an error instead.

@cppforlife, any other background or objections to someone making a PR and adding tests?

**Comment by geofffranks** [comment]
another case - updating cloud config when not logged in results in a 0-length post error:

```
Using environment 'https://10.0.48.4:25555' as anonymous user

Continue? [yN]: y

Updating cloud config:
  Performing request POST 'https://10.0.48.4:25555/cloud_configs':
    Performing POST request:
      Retry: Post https://10.0.48.4:25555/cloud_configs: http: ContentLength=7195 with Body length 0

Exit code 1
```

**Comment by cppforlife** [comment]
@dpb587-pivotal i dont have an objection to turning those into errors.

@geofffranks that's an unrelated problem. happens when you are unauthed.

**Comment by cjcjameson** [comment]
Hi there, we ran into the second issue that @geofffranks brought up -- the `update-cloud-config` error message when unauthed doesn't help diagnose the issue. Has there been motion on this topic? Should we file a separate issue for this?

<details><summary>Error output we see</summary>

```
$ bosh -e aws-bosh update-cloud-config --vars-file=<(terraform output --json) ../cloud-config.yml
Using environment '10.0.0.6' as client 'admin'

Fetching diff result:
  Performing request POST 'https://10.0.0.6:25555/cloud_configs/diff':
    Performing POST request:
      Retry: Post https://10.0.0.6:25555/cloud_configs/diff: http: ContentLength=1220 with Body length 0

Exit code 1

$ bosh -e aws-bosh login
Using environment '10.0.0.6' as client 'admin'

Failed to login to '10.0.0.6'

Invalid credentials

Exit code 1
```

</details>

**Comment by freddesbiens** [comment]
Validated that this is still an issue. Closing and reopening this story so that gitbot will create a corresponding tracker story.
