### ISSUE TITLE
update-cloud-config 500s if missing variables - no nice error message about missing variables

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#214]
I've a new bosh+credhub (if that's relevant) and I tried to update cloud config and it 500'd:

```
$ cd bosh-deployment
$ bosh2 update-cloud-config virtualbox/cloud-config.yml
Using environment '192.168.50.6' as user 'admin' (openid, bosh.admin)

Continue? [yN]: y

Updating cloud config:
  Director responded with non-successful status code '500' response ''
```

Looking inside `bosh/0` logs:

```
E, [2017-05-04 00:56:55 #6805] [] ERROR -- Director: NetAddr::ValidationError - Could not auto-detect IP version for '((internal_cidr))'.:
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/netaddr-1.5.1/lib/ip_math.rb:54:in `detect_ip_version'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/netaddr-1.5.1/lib/cidr.rb:157:in `create'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/manual_network_subnet.rb:15:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/manual_network.rb:18:in `block in parse'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/manual_network.rb:17:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/manual_network.rb:17:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:62:in `block in parse_networks'
```

Could the CLI please display the missing variables in the `bosh update-cloud-config` output instead of 500 status?

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/141743773

**Comment by dpb587-pivotal** [comment]
Fixed in [director/v262](https://github.com/cloudfoundry/bosh/releases/tag/v262) by not requiring cloud-configs to be fully interpolated at update time.
