### ISSUE TITLE
bosh create-env panic

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-cli#239]
```
$ bosh --version
version 2.0.25-687a73d-2017-06-07T23:31:58Z

Succeeded

$ bosh create-env ~/workspace/bosh-deployment/bosh.yml -o ~/workspace/bosh-deployment/aws/cpi.yml -o ~/workspace/bosh-deployment/bosh-lite.yml  -o ~/workspace/bosh-deployment/jumpbox-user.yml -o ops-bosh-lite.yml -l <(bbl bosh-deployment-vars) --vars-store ./creds.yml
Deployment manifest: '/Users/amitgupta/workspace/bosh-deployment/bosh.yml'
Deployment state: '/Users/amitgupta/workspace/bosh-deployment/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-warden-cpi'... Finished (00:00:00)
  Downloading release 'garden-linux'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-linux'... Finished (00:00:01)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:01)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:05)

Started installing CPI
  Compiling package 'golang_1.7/c82ff355bb4bd412a4397dba778682293cd4f392'...[CLI] 2017/06/08 10:58:10 ERROR - Panic: interface conversion: pkg.Compilable is *pkg.CompiledPackage, not *pkg.Package
********************
goroutine 1 [running]:
runtime/debug.Stack(0x739e40, 0xc4201e4000, 0x4e)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
main.handlePanic()
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:110 +0x2e1
panic(0x6c0a80, 0xc42023f380)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cloudfoundry/bosh-cli/cmd.Cmd.Execute.func1(0xc420166448)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/cmd.go:47 +0xe7
panic(0x6c0a80, 0xc42023f380)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cloudfoundry/bosh-cli/installation/pkg.(*compiler).Compile(0xc4203d8900, 0xaf6160, 0xc420472600, 0x0, 0x0, 0x0, 0x0, 0xc420439800, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/installation/pkg/compiler.go:89 +0x1537
github.com/cloudfoundry/bosh-cli/state/job.(*dependencyCompiler).compilePackages.func1(0xb31188, 0xed0cb8732)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/state/job/dependency_compiler.go:115 +0x70
github.com/cloudfoundry/bosh-cli/ui.(*stage).Perform(0xc42033bae0, 0xc42033bb30, 0x47, 0xc420111200, 0x2, 0xc42033bb30)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/ui/stage.go:47 +0x158
github.com/cloudfoundry/bosh-cli/state/job.(*dependencyCompiler).compilePackages(0xc42034ea20, 0xc420111180, 0x2, 0x2, 0xaf0640, 0xc42033bae0, 0x2, 0x0, 0x0, 0xc420253370, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/state/job/dependency_compiler.go:133 +0x304
github.com/cloudfoundry/bosh-cli/state/job.(*dependencyCompiler).Compile(0xc42034ea20, 0xc42013d1f0, 0x1, 0x1, 0xaf0640, 0xc42033bae0, 0x0, 0x0, 0xc4201578b8, 0xc420253370, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/state/job/dependency_compiler.go:50 +0x1f5
github.com/cloudfoundry/bosh-cli/installation.(*packageCompiler).For(0xc4201110e0, 0xc42013d1f0, 0x1, 0x1, 0xaf0640, 0xc42033bae0, 0xf, 0xc42027fe90, 0xc42027f6e0, 0x2f, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/installation/package_compiler.go:38 +0x8c
github.com/cloudfoundry/bosh-cli/installation.(*installer).Install(0xc4204f4600, 0xc420240958, 0x4, 0xc420253370, 0xa, 0xc4202533a0, 0xf, 0xc42027fe90, 0xc42027f6e0, 0x2f, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/installation/installer.go:70 +0x444
github.com/cloudfoundry/bosh-cli/cpi/release.CpiInstaller.installCpiRelease.func1(0xaf0640, 0xc42033bae0, 0xe383723, 0xb14620)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cpi/release/installer.go:37 +0xa4
github.com/cloudfoundry/bosh-cli/ui.(*stage).PerformComplex(0xc420264b90, 0x78786d, 0xe, 0xc42034ea50, 0xaeb840, 0xc42027a6e0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/ui/stage.go:68 +0x2c2
github.com/cloudfoundry/bosh-cli/cpi/release.CpiInstaller.installCpiRelease(0xce9778, 0xc42025b0c0, 0xaeb580, 0xc4200d1c30, 0x0, 0xaf04c0, 0xc4204f4600, 0xc420240958, 0x4, 0xc420253370, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cpi/release/installer.go:39 +0x1a4
github.com/cloudfoundry/bosh-cli/cpi/release.CpiInstaller.WithInstalledCpiRelease(0xce9778, 0xc42025b0c0, 0xaeb580, 0xc4200d1c30, 0x0, 0xc420240958, 0x4, 0xc420253370, 0xa, 0xc4202533a0, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cpi/release/installer.go:50 +0x14c
github.com/cloudfoundry/bosh-cli/cmd.(*DeploymentPreparer).PrepareDeployment(0xc42025e1e0, 0xaf0640, 0xc420264b90, 0x0, 0x0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/deployment_preparer.go:203 +0xd45
github.com/cloudfoundry/bosh-cli/cmd.(*CreateEnvCmd).Run(0xc42015a570, 0xaf0640, 0xc420264b90, 0xaf9160, 0xc420077680, 0xc42023a000, 0xd81, 0x1e00, 0x7fff5fbff868, 0x33, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/create_env.go:25 +0x26c
github.com/cloudfoundry/bosh-cli/cmd.Cmd.Execute(0x803fc0, 0x6c828f, 0xe, 0xc4200160a1, 0x1c, 0xaf9160, 0xc420077680, 0x0, 0x0, 0x0, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/cmd.go:74 +0x1062
main.main()
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:35 +0x75d

********************
Exit code 1
```

**Comment by cppforlife** [comment]
@Amit-PivotalLabs your cpi is compiled?

> Compiling package 'golang_1.7/c82ff355bb4bd412a4397dba778682293cd4f392'...[CLI] 2017/06/08 10:58:10 ERROR - Panic: interface conversion: pkg.Compilable is *pkg.CompiledPackage, not *pkg.Package

we currently dont support compiled cpis.
