### ISSUE TITLE
CLI panic in "Downloading remote release"

### ISSUE THREAD

**Issue by krumts** [cloudfoundry/bosh-cli#311]
Hi,

over the last 2 days I ran 3 times into the following error, while trying to update different bosh deployments:
```
Task 1279411
Task 1279412
Task 1279411 | 14:55:40 | Downloading remote release: Downloading remote release (00:00:16)
Task 1279411 | 14:55:56 | Verifying remote release: Verifying remote release (00:00:01)
Task 1279411 | 14:55:57 | Extracting release: Extracting release (00:00:03)
Task 1279411 | 14:56:00 | Verifying manifest: Verifying manifest (00:00:00)
Task 1279411 | 14:56:01 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 1279411 | 14:56:01 | Creating new packages: auctioneer/a9c5682b82fbaba29ac221b464b68a71be2bc62ac0cff7622d14efb7147cd9a8 (00:00:00)
Task 1279411 | 14:56:01 | Creating new packages: bbs/0a8c50f867b2b79d69de3151e2ab484133b222b9e7605e6719eb8f837e20358b (00:00:00)
Task 1279411 | 14:56:01 | Creating new packages: benchmark-bbs/cb78cda8a8612d3a22b757f261b69df3bfd12b800a6f5ebd2440caaebc2e4bf6 (00:00:01)
Task 1279411 | 14:56:02 | Creating new packages: buildpack_app_lifecycle/f91a421e6299e4d8f1df505f5527dd5084891f75bfa4a67bb9d8072f3071532c (00:00:00)
Task 1279411 | 14:56:02 | Creating new packages: cfdot/b7396b53edc3fc664b8a8b3a672d8a6c5e30894974f7c80d36d1d2cf17c58cb5 (00:00:00)
Task 1279411 | 14:56:02 | Creating new packages: diego-sshd/1b7eed8079b29008a88a2cbb90b860ca8ecb19e5198fb7395bbf36556f4e05fd
Task 1279412 done


Task 1279411 Started  Wed Sep  6 14:55:40 UTC 2017
Task 1279411 Finished Wed Sep  6 14:56:02 UTC 2017
Task 1279411 Duration 00:00:22panic: unmarshal chunk '{"time":1504709762,"stage":"Creating new p{"time":1504709740,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}'

goroutine 24 [running]:
panic(0xc78ac0, 0xc420326ad0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudfoundry/bosh-cli/ui/task.(*ReporterImpl).showEvent(0xc4203ba180, 0x1385b4, 0xc42034e000, 0xc3)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/ui/task/reporter.go:110 +0x1a5e
github.com/cloudfoundry/bosh-cli/ui/task.(*ReporterImpl).TaskOutputChunk(0xc4203ba180, 0x1385b4, 0xc42029e000, 0x994, 0x8000)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/ui/task/reporter.go:94 +0x26c
github.com/cloudfoundry/bosh-cli/director.(*taskReporterWriter).Write(0xc420534b80, 0xc42029e000, 0x994, 0x8000, 0x994, 0x12c5220, 0xc420014100)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:155 +0x63
io.copyBuffer(0x12c5820, 0xc420534b80, 0x12c74e0, 0xc42001e640, 0xc42029e000, 0x8000, 0x8000, 0xcffbe0, 0xc4204e8400, 0x12c74e0)
	/usr/local/go/src/io/io.go:392 +0x260
io.Copy(0x12c5820, 0xc420534b80, 0x12c74e0, 0xc42001e640, 0xc42001e640, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
github.com/cloudfoundry/bosh-cli/director.ClientRequest.readResponse(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/client_request.go:249 +0x2a4
github.com/cloudfoundry/bosh-cli/director.ClientRequest.RawGet(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/client_request.go:109 +0x350
github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.reportOutputChunk(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:172 +0x248
github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.WaitForCompletion(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:108 +0x2b5
github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.waitForResult(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:129 +0xa2
github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.PostResult(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:63 +0x157
github.com/cloudfoundry/bosh-cli/director.Client.UploadReleaseURL(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/releases.go:303 +0x334
github.com/cloudfoundry/bosh-cli/director.DirectorImpl.UploadReleaseURL(0xc42030d700, 0x17, 0x0, 0x0, 0x12d4ce0, 0xc4203b4680, 0x12cde20, 0xc4202c6330, 0x12d5040, 0xc4202504b0, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/director/releases.go:219 +0xbe
github.com/cloudfoundry/bosh-cli/director.(*DirectorImpl).UploadReleaseURL(0xc4202fe0c0, 0xc420016640, 0x4a, 0xc4203b0a20, 0x28, 0x12d0000, 0xc4202504b0, 0xc42030d700)
	<autogenerated>:171 +0xe7
github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.uploadRemote(0xc4202c6fd0, 0x12c88a0, 0xc4203ba240, 0x12d8ae0, 0xc4202fe0c0, 0xc4202c6fe0, 0x12d3660, 0xc420183c20, 0x12d71e0, 0xc42001fe00, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:62 +0x84
github.com/cloudfoundry/bosh-cli/cmd.(UploadReleaseCmd).(github.com/cloudfoundry/bosh-cli/cmd.uploadRemote)-fm(0xc420016640, 0x4a, 0x0, 0x0, 0x0, 0xc4202ee8b0, 0xa, 0xc420460400, 0x3, 0x4, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:53 +0x73
github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.uploadIfNecessary(0xc4202c6fd0, 0x12c88a0, 0xc4203ba240, 0x12d8ae0, 0xc4202fe0c0, 0xc4202c6fe0, 0x12d3660, 0xc420183c20, 0x12d71e0, 0xc42001fe00, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:149 +0xe3
github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.Run(0xc4202c6fd0, 0x12c88a0, 0xc4203ba240, 0x12d8ae0, 0xc4202fe0c0, 0xc4202c6fe0, 0x12d3660, 0xc420183c20, 0x12d71e0, 0xc42001fe00, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:53 +0x3c7
github.com/cloudfoundry/bosh-cli/cmd.(*UploadReleaseCmd).Run(0xc4203ba420, 0xc420016640, 0x4a, 0x0, 0x0, 0x0, 0xc4202ee8b0, 0xa, 0xc420460400, 0x3, ...)
	<autogenerated>:257 +0x9d
github.com/cloudfoundry/bosh-cli/cmd.ReleaseManager.createAndUploadRelease(0x12c8620, 0xc4203b46c0, 0x12c8720, 0xc4203ba420, 0x5, 0xc4202ee8b0, 0xa, 0xc4202ee8f8, 0x7, 0xc420016640, ...)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/release_manager.go:144 +0x1c5
github.com/cloudfoundry/bosh-cli/cmd.ReleaseManager.parallelCreateAndUpload.func1(0xc70d80, 0xc42045f620, 0xc420029768, 0x1)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/release_manager.go:65 +0x7f
github.com/cloudfoundry/bosh-cli/cmd.WorkerPool.spawnWorker.func1(0xc42045f620, 0xc42045f740, 0xc42045f680, 0xc42045f800)
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/worker_pool.go:63 +0x6e
created by github.com/cloudfoundry/bosh-cli/cmd.WorkerPool.spawnWorker
	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/worker_pool.go:73 +0x5d

```

The bosh cli version we use is: version 2.0.33-c845370-2017-08-18T23:13:10Z

The error occurred sporadically and retry helped in all 3 cases (these were three different deployments done against the same director).
So far I haven't been able to find a way to reproduce the issue on purpose.

Any suggestions what could be going wrong?

Thanks in advance!

**Comment by cppforlife** [comment]
@krumts could you include `bosh task 1279412 --event` and `bosh task 1279411  --event` for us to take a look? appears to be a race condition for parallel tracking of tasks.

**Comment by krumts** [comment]
@cppforlife here the requested output:
```
Task 1279412

{"time":1504709740,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}
{"time":1504709759,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"finished","progress":100}
{"time":1504709759,"stage":"Verifying remote release","tags":[],"total":1,"task":"Verifying remote release","index":1,"state":"started","progress":0}
{"time":1504709760,"stage":"Verifying remote release","tags":[],"total":1,"task":"Verifying remote release","index":1,"state":"finished","progress":100}
{"time":1504709760,"stage":"Extracting release","tags":[],"total":1,"task":"Extracting release","index":1,"state":"started","progress":0}
{"time":1504709764,"stage":"Extracting release","tags":[],"total":1,"task":"Extracting release","index":1,"state":"finished","progress":100}
{"time":1504709764,"stage":"Verifying manifest","tags":[],"total":1,"task":"Verifying manifest","index":1,"state":"started","progress":0}
{"time":1504709764,"stage":"Verifying manifest","tags":[],"total":1,"task":"Verifying manifest","index":1,"state":"finished","progress":100}
{"time":1504709764,"stage":"Resolving package dependencies","tags":[],"total":1,"task":"Resolving package dependencies","index":1,"state":"started","progress":0}
{"time":1504709764,"stage":"Resolving package dependencies","tags":[],"total":1,"task":"Resolving package dependencies","index":1,"state":"finished","progress":100}
{"time":1504709764,"stage":"Creating new packages","tags":[],"total":1,"task":"cflinuxfs2/5f70db8053be8ecde96b98708eb201e17b329f92","index":1,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new packages","tags":[],"total":1,"task":"cflinuxfs2/5f70db8053be8ecde96b98708eb201e17b329f92","index":1,"state":"finished","progress":100}
{"time":1504709770,"stage":"Processing 2 existing jobs","tags":[],"total":1,"task":"Processing 2 existing jobs","index":1,"state":"started","progress":0}
{"time":1504709770,"stage":"Processing 2 existing jobs","tags":[],"total":1,"task":"Processing 2 existing jobs","index":1,"state":"finished","progress":100}
{"time":1504709770,"stage":"Release has been created","tags":[],"total":1,"task":"cflinuxfs2/1.148.0","index":1,"state":"started","progress":0}
{"time":1504709770,"stage":"Release has been created","tags":[],"total":1,"task":"cflinuxfs2/1.148.0","index":1,"state":"finished","progress":100}

Task 1279412 done


Task 1279411

{"time":1504709740,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}
{"time":1504709756,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"finished","progress":100}
{"time":1504709756,"stage":"Verifying remote release","tags":[],"total":1,"task":"Verifying remote release","index":1,"state":"started","progress":0}
{"time":1504709757,"stage":"Verifying remote release","tags":[],"total":1,"task":"Verifying remote release","index":1,"state":"finished","progress":100}
{"time":1504709757,"stage":"Extracting release","tags":[],"total":1,"task":"Extracting release","index":1,"state":"started","progress":0}
{"time":1504709760,"stage":"Extracting release","tags":[],"total":1,"task":"Extracting release","index":1,"state":"finished","progress":100}
{"time":1504709760,"stage":"Verifying manifest","tags":[],"total":1,"task":"Verifying manifest","index":1,"state":"started","progress":0}
{"time":1504709760,"stage":"Verifying manifest","tags":[],"total":1,"task":"Verifying manifest","index":1,"state":"finished","progress":100}
{"time":1504709761,"stage":"Resolving package dependencies","tags":[],"total":1,"task":"Resolving package dependencies","index":1,"state":"started","progress":0}
{"time":1504709761,"stage":"Resolving package dependencies","tags":[],"total":1,"task":"Resolving package dependencies","index":1,"state":"finished","progress":100}
{"time":1504709761,"stage":"Creating new packages","tags":[],"total":21,"task":"auctioneer/a9c5682b82fbaba29ac221b464b68a71be2bc62ac0cff7622d14efb7147cd9a8","index":1,"state":"started","progress":0}
{"time":1504709761,"stage":"Creating new packages","tags":[],"total":21,"task":"auctioneer/a9c5682b82fbaba29ac221b464b68a71be2bc62ac0cff7622d14efb7147cd9a8","index":1,"state":"finished","progress":100}
{"time":1504709761,"stage":"Creating new packages","tags":[],"total":21,"task":"bbs/0a8c50f867b2b79d69de3151e2ab484133b222b9e7605e6719eb8f837e20358b","index":2,"state":"started","progress":0}
{"time":1504709761,"stage":"Creating new packages","tags":[],"total":21,"task":"bbs/0a8c50f867b2b79d69de3151e2ab484133b222b9e7605e6719eb8f837e20358b","index":2,"state":"finished","progress":100}
{"time":1504709761,"stage":"Creating new packages","tags":[],"total":21,"task":"benchmark-bbs/cb78cda8a8612d3a22b757f261b69df3bfd12b800a6f5ebd2440caaebc2e4bf6","index":3,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"benchmark-bbs/cb78cda8a8612d3a22b757f261b69df3bfd12b800a6f5ebd2440caaebc2e4bf6","index":3,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"buildpack_app_lifecycle/f91a421e6299e4d8f1df505f5527dd5084891f75bfa4a67bb9d8072f3071532c","index":4,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"buildpack_app_lifecycle/f91a421e6299e4d8f1df505f5527dd5084891f75bfa4a67bb9d8072f3071532c","index":4,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"cfdot/b7396b53edc3fc664b8a8b3a672d8a6c5e30894974f7c80d36d1d2cf17c58cb5","index":5,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"cfdot/b7396b53edc3fc664b8a8b3a672d8a6c5e30894974f7c80d36d1d2cf17c58cb5","index":5,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"diego-sshd/1b7eed8079b29008a88a2cbb90b860ca8ecb19e5198fb7395bbf36556f4e05fd","index":6,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"diego-sshd/1b7eed8079b29008a88a2cbb90b860ca8ecb19e5198fb7395bbf36556f4e05fd","index":6,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"docker_app_lifecycle/1415c78be312071e7f2e52faace335146a14fe7a1cf85a6274487f3a8b895b7f","index":7,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"docker_app_lifecycle/1415c78be312071e7f2e52faace335146a14fe7a1cf85a6274487f3a8b895b7f","index":7,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"file_server/83089fcccd9678c83dcef505ef60562d8d3491588807e4eea0dc0ce42e80b1ea","index":8,"state":"started","progress":0}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"file_server/83089fcccd9678c83dcef505ef60562d8d3491588807e4eea0dc0ce42e80b1ea","index":8,"state":"finished","progress":100}
{"time":1504709762,"stage":"Creating new packages","tags":[],"total":21,"task":"golang/81204f38eebc29dbd249b8c27638f4de9331a3e263763b2b276f20cd22517904","index":9,"state":"started","progress":0}
{"time":1504709765,"stage":"Creating new packages","tags":[],"total":21,"task":"golang/81204f38eebc29dbd249b8c27638f4de9331a3e263763b2b276f20cd22517904","index":9,"state":"finished","progress":100}
{"time":1504709765,"stage":"Creating new packages","tags":[],"total":21,"task":"golang-windows/b336b2341205cb209c29c1523e04e784332aee8a2f4918929810e97a527e35b1","index":10,"state":"started","progress":0}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"golang-windows/b336b2341205cb209c29c1523e04e784332aee8a2f4918929810e97a527e35b1","index":10,"state":"finished","progress":100}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"healthcheck/98128c9a91f6f03f534a8f37a9ff474264766b18d24886c3388304efdb12b410","index":11,"state":"started","progress":0}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"healthcheck/98128c9a91f6f03f534a8f37a9ff474264766b18d24886c3388304efdb12b410","index":11,"state":"finished","progress":100}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"healthcheck_windows/b08fb4633a0042a0bcb266a2e62d525bc5d0e53f581cd993b7a4fec3a6f224fb","index":12,"state":"started","progress":0}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"healthcheck_windows/b08fb4633a0042a0bcb266a2e62d525bc5d0e53f581cd993b7a4fec3a6f224fb","index":12,"state":"finished","progress":100}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"locket/1c366566ae48004b2195c74554a1fa75f1e5348120dbd327b28aca4694c1866e","index":13,"state":"started","progress":0}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"locket/1c366566ae48004b2195c74554a1fa75f1e5348120dbd327b28aca4694c1866e","index":13,"state":"finished","progress":100}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"pid_utils/60882ec87f35d03935d851331cf5d302771104fe14d64318f31465f262b22164","index":14,"state":"started","progress":0}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"pid_utils/60882ec87f35d03935d851331cf5d302771104fe14d64318f31465f262b22164","index":14,"state":"finished","progress":100}
{"time":1504709767,"stage":"Creating new packages","tags":[],"total":21,"task":"rep/50d06242e5bf74e9bac0625f57f0edde575ab38390e4d74875bee23608a506b7","index":15,"state":"started","progress":0}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"rep/50d06242e5bf74e9bac0625f57f0edde575ab38390e4d74875bee23608a506b7","index":15,"state":"finished","progress":100}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"rep_windows/a2543b1b336bafb7b7a1adb31d80fa94ae58f44aaa3da41bd47adafcfba02e60","index":16,"state":"started","progress":0}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"rep_windows/a2543b1b336bafb7b7a1adb31d80fa94ae58f44aaa3da41bd47adafcfba02e60","index":16,"state":"finished","progress":100}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"route_emitter/a2e5bfd556dc71876f9d0742aca6e736afc9b6162d550bb3987d0cea4b6a4978","index":17,"state":"started","progress":0}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"route_emitter/a2e5bfd556dc71876f9d0742aca6e736afc9b6162d550bb3987d0cea4b6a4978","index":17,"state":"finished","progress":100}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"route_emitter_windows/939a79f3fc289ff86172a0e0bb45589c520b4b582f537b548778e6d349cd7961","index":18,"state":"started","progress":0}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"route_emitter_windows/939a79f3fc289ff86172a0e0bb45589c520b4b582f537b548778e6d349cd7961","index":18,"state":"finished","progress":100}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"ssh_proxy/0f0e373fdd33c7880d87ec7cdd4b073fbfe1a7f922c356ec0cd89e07b19f2018","index":19,"state":"started","progress":0}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"ssh_proxy/0f0e373fdd33c7880d87ec7cdd4b073fbfe1a7f922c356ec0cd89e07b19f2018","index":19,"state":"finished","progress":100}
{"time":1504709768,"stage":"Creating new packages","tags":[],"total":21,"task":"vizzini/71f674b6fbf34f699aa9e523061b36f95ced9d3f6263a892a9d09171dac138da","index":20,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new packages","tags":[],"total":21,"task":"vizzini/71f674b6fbf34f699aa9e523061b36f95ced9d3f6263a892a9d09171dac138da","index":20,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new packages","tags":[],"total":21,"task":"windows_app_lifecycle/8a5fdd086025a9730e347dd9d1bfb2b15af0d3582d3e6ef7fef5afbae7acf59f","index":21,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new packages","tags":[],"total":21,"task":"windows_app_lifecycle/8a5fdd086025a9730e347dd9d1bfb2b15af0d3582d3e6ef7fef5afbae7acf59f","index":21,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"auctioneer/8e3d5584619bba5366bdcc7c908d00e47626b4ec3c111c4522b3e008a3618ff0","index":1,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"auctioneer/8e3d5584619bba5366bdcc7c908d00e47626b4ec3c111c4522b3e008a3618ff0","index":1,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"bbs/4659809df75481cf238635f9ece65cfb2897a1e0c968807a9e4d32c7f13c6928","index":2,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"bbs/4659809df75481cf238635f9ece65cfb2897a1e0c968807a9e4d32c7f13c6928","index":2,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"benchmark-bbs/6310033c6997a79d4ad29eb171bce168d6aa5913a6adc381e7c30645561d2eec","index":3,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"benchmark-bbs/6310033c6997a79d4ad29eb171bce168d6aa5913a6adc381e7c30645561d2eec","index":3,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"cfdot/149bec5eb3953c08f59df65d18240b0dec81aefc9745c8488e6d4d56bac3d5f1","index":4,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"cfdot/149bec5eb3953c08f59df65d18240b0dec81aefc9745c8488e6d4d56bac3d5f1","index":4,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"file_server/d5d978e87602f3ef0dbefa4aff612d30cc24116e5e57565b82bb086ffccd69b9","index":5,"state":"started","progress":0}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"file_server/d5d978e87602f3ef0dbefa4aff612d30cc24116e5e57565b82bb086ffccd69b9","index":5,"state":"finished","progress":100}
{"time":1504709769,"stage":"Creating new jobs","tags":[],"total":12,"task":"locket/00e181a78f4a383e9da27232ca9e1550fda5b0cd869907bb92acb89830ff984b","index":6,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"locket/00e181a78f4a383e9da27232ca9e1550fda5b0cd869907bb92acb89830ff984b","index":6,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"rep/00670557b743d6bae5c53f9b9df78fff44c60720800e45ce4ec001fbc333e0c0","index":7,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"rep/00670557b743d6bae5c53f9b9df78fff44c60720800e45ce4ec001fbc333e0c0","index":7,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"rep_windows/54c96d7f4a28dcc167988ee5e83cc907fcc417745c46dfd3f9ca469278657ab0","index":8,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"rep_windows/54c96d7f4a28dcc167988ee5e83cc907fcc417745c46dfd3f9ca469278657ab0","index":8,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"route_emitter/e1e3a96d36061888fe24aa6d2e80224461243ee477a88059cf7aab5b9a5c2043","index":9,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"route_emitter/e1e3a96d36061888fe24aa6d2e80224461243ee477a88059cf7aab5b9a5c2043","index":9,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"route_emitter_windows/7b3f02be19f6b2c4fd4d079f08f0da6dbb5842a63a77d073d4e3e498371f95c3","index":10,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"route_emitter_windows/7b3f02be19f6b2c4fd4d079f08f0da6dbb5842a63a77d073d4e3e498371f95c3","index":10,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"ssh_proxy/ba8dcf46ec7e709e17b5f147a1269b27368b66d0bb65dd657e88cfd8ab466f04","index":11,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"ssh_proxy/ba8dcf46ec7e709e17b5f147a1269b27368b66d0bb65dd657e88cfd8ab466f04","index":11,"state":"finished","progress":100}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"vizzini/37789c4004aefbfffc59b43623b6763ab74215d52419518daca1c7ea43ddf8b6","index":12,"state":"started","progress":0}
{"time":1504709770,"stage":"Creating new jobs","tags":[],"total":12,"task":"vizzini/37789c4004aefbfffc59b43623b6763ab74215d52419518daca1c7ea43ddf8b6","index":12,"state":"finished","progress":100}
{"time":1504709770,"stage":"Release has been created","tags":[],"total":1,"task":"diego/1.25.1","index":1,"state":"started","progress":0}
{"time":1504709770,"stage":"Release has been created","tags":[],"total":1,"task":"diego/1.25.1","index":1,"state":"finished","progress":100}

Task 1279411 done

Succeeded

```

Hope this helps.

**Comment by jpalermo** [comment]
We've hit this in 3 of our last 6 builds when trying to deploy bosh-release.

**Comment by cppforlife** [comment]
Fix is in: https://github.com/cloudfoundry/bosh-cli/commit/f58b3a1827c1f4359397485d781c16f102e4b430. going through pipes.
