### ISSUE TITLE
Please update config-server to latest; resolve "dep ensure" panic

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#458]
I'm trying to support `bosh deploy --vars-store` for CFCR project which requires `organization` on its certificates (see https://github.com/cloudfoundry-incubator/kubo-deployment/issues/334#issuecomment-408860409)

I have a PR for config-server https://github.com/cloudfoundry/config-server/pull/12 but cannot test it in bosh-cli due to `dep ensure` errors:

```
$ dep ensure -update
panic: version queue is empty, should not happen

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc4200d3b00, 0xc420541180, 0xc4202f7230, 0x1, 0x1, 0x0, 0xc4202f7230)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/gps/solver.go:918 +0x4d7
github.com/golang/dep/gps.(*solver).createVersionQueue(0xc4200d3b00, 0xc4206ad3c1, 0x14, 0x0, 0x0, 0xc4202f7230, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/gps/solver.go:905 +0x93f
github.com/golang/dep/gps.(*solver).solve(0xc4200d3b00, 0x15e5340, 0xc420026190, 0x0, 0xc4200240a4, 0x41)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/gps/solver.go:508 +0x5b7
github.com/golang/dep/gps.(*solver).Solve(0xc4200d3b00, 0x15e5340, 0xc420026190, 0x185beb8, 0xc4200240c5, 0x20, 0xc42021c750)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/gps/solver.go:448 +0xc8
main.(*ensureCommand).runUpdate(0xc420175ac0, 0xc4200b6980, 0xc4201907d0, 0x0, 0x0, 0xc4200790e0, 0x15e8d00, 0xc420079740, 0xc4200240a4, 0x41, ...)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:388 +0x2c0
main.(*ensureCommand).Run(0xc420175ac0, 0xc4200b6980, 0xc4201907d0, 0x0, 0x0, 0x0, 0x0)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:217 +0x7ab
main.(*Config).Run(0xc420078fc0, 0x0)
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/cmd/dep/main.go:244 +0x1150
main.main()
	/Users/drnic/Projects/gopath/src/github.com/golang/dep/cmd/dep/main.go:70 +0x52c
```

**Comment by jfmyers9** [comment]
Hi @drnic,

This should be fixed on the `develop` branch as of https://github.com/cloudfoundry/bosh-cli/commit/dac8ffd782c3659c7509dd18c4080c05409cea73. The `dep ensure -update` panic was actually a result of https://github.com/cloudfoundry/bosh-cli/blob/master/Gopkg.toml#L37-L40.

Best,

@jfmyers9
