### ISSUE TITLE
panic whilst performing create-env

### ISSUE THREAD

**Issue by irbekrm** [cloudfoundry/bosh-cli#477]
Hi, I was running `bosh create-env` and it failed with the following stack trace: 

```
  Updating instance 'bosh/0'...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x106b4f3]

goroutine 1316 [running]:
io.copyBuffer(0x1bfdd00, 0xc420376840, 0x0, 0x0, 0xc42067a000, 0x8000, 0x8000, 0xc420376840, 0xc420376840, 0x19cb9c0)
        /usr/local/go/src/io/io.go:400 +0x143
io.Copy(0x1bfdd00, 0xc420376840, 0x0, 0x0, 0x20, 0x20, 0x0)
        /usr/local/go/src/io/io.go:362 +0x5a
net.genericReadFrom(0x1bfc140, 0xc4200b61f8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:597 +0x84
net.(*TCPConn).readFrom(0xc4200b61f8, 0x0, 0x0, 0xc4205d2e08, 0x100e04d, 0x1998080)
        /usr/local/go/src/net/tcpsock_posix.go:51 +0x4d
net.(*TCPConn).ReadFrom(0xc4200b61f8, 0x0, 0x0, 0x25e5ae8, 0xc4200b61f8, 0xc42001c001)
        /usr/local/go/src/net/tcpsock.go:103 +0x5f
io.copyBuffer(0x1bfc140, 0xc4200b61f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a9ff80, 0x0, 0x1bfc140)
        /usr/local/go/src/io/io.go:386 +0x31a
io.Copy(0x1bfc140, 0xc4200b61f8, 0x0, 0x0, 0x0, 0x0, 0xc4205d2f68)
        /usr/local/go/src/io/io.go:362 +0x5a
github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start.func3(0x1c0bfa0, 0xc4200b61f8, 0x0, 0x0, 0xc420402b90, 0xc42036c780)
        /tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:85 +0xc3
created by github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start
        /tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:84 +0x314
```

(Using bosh version 5.0.1-2432e5e9-2018-07-18T21:41:03Z)

**Comment by mfine30** [comment]
Hey @irbekrm could you try upgrading to a more recent version of the CLI and see if you still hit this issue? It looks to be the same as #462

**Comment by irbekrm** [comment]
Thanks, it worked second time round:

Found the fix: https://github.com/cloudfoundry/bosh-cli/commit/484e43a36e1b156fd72bf950af0d144c2bca2006

**Comment by mfine30** [comment]
Great. I'm going to close this issue, but let us know if you still hit any problems.
