### ISSUE TITLE
Running deploy with a certain variable value panics

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-cli#583]
Running a deploy with a variable containing quotes as value causes a panic with the latest cli `6.4.10`. The problem does not occur with `6.4.9`

Might be related to https://github.com/cloudfoundry/bosh-cli/pull/581.

```
bosh -n -d deployment deploy manifest --var=key='""'
```

```
[CLI] 2021/12/21 10:22:04 ERROR - Panic: runtime error: index out of range [0] with length 0
********************
goroutine 1 [running]:
runtime/debug.Stack()
	/var/vcap/packages/golang-1-linux/src/runtime/debug/stack.go:24 +0x65
main.handlePanic()
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:117 +0x23a
panic({0x1be43a0, 0xc000034378})
	/var/vcap/packages/golang-1-linux/src/runtime/panic.go:1038 +0x215
github.com/cloudfoundry/bosh-cli/director/template.trimWrappingQuotes({0x7ff7bfefe696, 0xc0009ceae8})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/director/template/var_kv.go:16 +0x8f
github.com/cloudfoundry/bosh-cli/director/template.trimWrappingQuotes({0x7ff7bfefe696, 0x2})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/director/template/var_kv.go:18 +0x6e
github.com/cloudfoundry/bosh-cli/director/template.(*VarKV).UnmarshalFlag(0xc000096b00, {0x7ff7bfefe680, 0x18})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/director/template/var_kv.go:46 +0xfc
github.com/jessevdk/go-flags.convertUnmarshal({0x7ff7bfefe680, 0x18}, {0x1ad3b40, 0xc000096b00, 0xc0009cec98})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/convert.go:173 +0x1bd
github.com/jessevdk/go-flags.convertUnmarshal({0x7ff7bfefe680, 0x18}, {0x1b563a0, 0xc000096b00, 0x105a185})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/convert.go:178 +0x231
github.com/jessevdk/go-flags.convert({0x7ff7bfefe680, 0xc000096b00}, {0x1b563a0, 0xc000096b00, 0xc00000c9a8}, {{0x1acd0c9, 0xc0009cee38}, 0xc00012c0c0})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/convert.go:189 +0x8e
github.com/jessevdk/go-flags.convert({0x7ff7bfefe680, 0xc00010ab20}, {0x1a69720, 0xc00010ab20, 0x1b0cec0}, {{0x1acd0c9, 0x197}, 0xc00012c0c0})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/convert.go:264 +0xc13
github.com/jessevdk/go-flags.(*Option).set(0xc00030a4e0, 0xc0009cf078)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/option.go:279 +0x126
github.com/jessevdk/go-flags.(*Parser).parseOption(0xc000802690, 0xc0009cf238, {0x7ff7bfefe67c, 0x3}, 0xc00030a4e0, 0x1, 0xc00007ed20)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/parser.go:549 +0x2e5
github.com/jessevdk/go-flags.(*Parser).parseLong(0xc0001ea000, 0xc0009cf238, {0x7ff7bfefe67c, 0x3}, 0xc000180001)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/parser.go:604 +0x131
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000802690, {0xc0001ac010, 0xc00016e8a0, 0xf})
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/vendor/github.com/jessevdk/go-flags/parser.go:282 +0x52a
github.com/cloudfoundry/bosh-cli/cmd.Factory.New({{{0x1f49620, 0xc0003fa340}, 0xc0003fa300, {0x1f3f1a8, 0xc0005cbfb0}, {0x1f0aec0, 0x26e18f8}, {0x1f2c1b8, 0xc000544240}, {0x1f249d0, ...}, ...}}, ...)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/cmd/factory.go:103 +0x3cc
main.main()
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/main.go:30 +0x1f3
```

**Comment by jpalermo** [comment]
Looks like a bad bounds check on our part, however in fixing it, we became confused about what the correct output should be.

With a manifest of:
```
some: ((key))
```
And a variable argument of ` --var=key='""'`
We get this using 6.4.9: `some: '""'`

Is that the desired interpolation?

Fixing the bounds checking causes it not to crash, but the output is this instead: `some: ""`

Those are behaviorally different. The old behavior is the desired one?

**Comment by danielfor** [comment]
Hi @friegger we were doing additional parsing for a specific case that affected empty strings, so we removed that additional parsing and left the code as it was before. The PR for that change is here:
https://github.com/cloudfoundry/bosh-cli/pull/584 and will be shipped in the a bosh-cli version soon .
