### ISSUE TITLE
CLI crashes on trying to select multiple columns to print

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/bosh-cli#636]
I've tried to use the `--column` option to only display the instance name and IP addresses:

```
bosh -d cf vms --column="instance,ips"
```

which yields a panic:
```
[CLI] 2023/12/04 15:37:20 ERROR - Panic: Failed to find header: instance_ips
********************
goroutine 1 [running]:
runtime/debug.Stack()
        /var/vcap/packages/golang-1-linux/src/runtime/debug/stack.go:24 +0x65
main.handlePanic()
        /tmp/build/4e5b1fab/bosh-cli/main.go:117 +0x23a
panic({0xf6e060, 0xc0001209b0})
        /var/vcap/packages/golang-1-linux/src/runtime/panic.go:838 +0x207
github.com/cloudfoundry/bosh-cli/v7/cmd.Cmd.Execute.func1()
        /tmp/build/4e5b1fab/bosh-cli/cmd/cmd.go:52 +0x6e
panic({0xf6e060, 0xc0001209b0})
        /var/vcap/packages/golang-1-linux/src/runtime/panic.go:844 +0x258
github.com/cloudfoundry/bosh-cli/v7/ui.(*ConfUI).PrintTable(0xc000044080, {{0xc0007f8120, 0xf}, {0x111296e, 0x3}, {0xc0001c6000, 0x8, 0x8}, {0xc0007f81b0, 0x1, ...}, ...})
        /tmp/build/4e5b1fab/bosh-cli/ui/conf_ui.go:87 +0xb0
github.com/cloudfoundry/bosh-cli/v7/cmd.VMsCmd.printDeployment({{0x1424d50, 0xc000044080}, {0x14297a8, 0xc0003fc000}, 0x5}, {0x1428960?, 0xc0003ee280?}, {0x0, 0x1, 0x0, ...}, ...)
        /tmp/build/4e5b1fab/bosh-cli/cmd/vms.go:140 +0x215
github.com/cloudfoundry/bosh-cli/v7/cmd.VMsCmd.Run({{0x1424d50, 0xc000044080}, {0x14297a8, 0xc0003fc000}, 0x5}, {0x0, 0x0, 0x0, {0x7ffe5fbbd4aa, 0x2}, ...})
        /tmp/build/4e5b1fab/bosh-cli/cmd/vms.go:53 +0x131
github.com/cloudfoundry/bosh-cli/v7/cmd.Cmd.Execute({{0x1183db8, {0xf9dcba, 0xe}, {0xc0000360a1, 0x4}, {{0x0, 0x0}, {0x0, 0x0}}, 0x0, ...}, ...})
        /tmp/build/4e5b1fab/bosh-cli/cmd/cmd.go:320 +0x31c5
main.main()
        /tmp/build/4e5b1fab/bosh-cli/main.go:35 +0x265
```

Selecting each column individually works fine:
```
bosh -d cf vms --column="instance"

(...)

Instance
api/01937b7b-c297-4115-a386-54cce6a5cafa
api/023d0fec-61ae-488a-bf64-5130effc93d0
api/0360a44a-564b-48a9-81ce-f15653bbc7c2
api/0627e1ea-cbda-4df7-a258-55ee793d5f1c
```

My assumption was that the `--columns` argument expects a comma-separated list of columns to print. This is unfortunately not well-documented on the [CLI docs](https://bosh.io/docs/cli-v2/) where it vaguely states:
```
--column=NAME Filter to show only given column(s)
```

I don't know if I'm using the CLI wrong but I know it shouldn't crash on me 😅

BOSH CLI version:
```
version 7.0.1-799538d1-2022-06-01T21:53:20Z
```

**Comment by jpalermo** [comment]
Looks like if you want multiple columns you need to specify the `--column` flag multiple times.

It would benefit from an update to the docs and better error handling though, so we'll leave this "open for contribution"

**Comment by nader-ziada** [comment]
I will work on adding a better error message and update the docs, PR coming soon

**Comment by jpalermo** [comment]
Fixed via PR above, closing.
